export const CHANGE_NODE          = 'CHANGE_NODE'
export const STOP_MOVE            = 'STOP_MOVE'
export const STOP_MOVE_CONNECTOR  = 'STOP_MOVE_CONNECTOR'
export const START_MOVE           = 'START_MOVE'
export const MOUSE_MOVE           = 'MOUSE_MOVE'
export const MOVE_NODE            = 'MOUSE_MOVE_NODE'
export const MOVE_CONNECTOR       = 'MOUSE_MOVE_CONNECTOR'
export const CANCEL_MOVE          = 'CANCEL_MOVE'
export const STOP_MOVE_NODE       = 'STOP_MOVE_NODE'
export const END_LOCATION         = 'ENDLOCATION'
export const SELECT_NODE          = 'SELECT_NODE'
export const SELECT_CONNECTOR     = 'SELECT_CONNECTOR'
export const HIGHLIGHT_CONNECTOR  = 'HIGHLIGHT_CONNECTOR'
export const HIGHLIGHT            = 'HIGHLIGHT';
export const CONNECTOR_END_VISIBILITY = 'CONNECTOR_END_VISIBILITY'
export const FRAME_READY          = 'FRAME_READY'
export const ADD_NODE             = 'ADD_NODE'

